mybatis-plus:
  mapper-locations: classpath*:mybatis/*/*Mapper.xml

spring:
  profiles:
    active: dev
  datasource:
    dynamic:
      primary: db1 #设置默认的数据源或者数据源组,默认值即为master
      strict: true #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        db1:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/sbd?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&tinyInt1isBit=false
          username: root
          password:
        db2:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/sbd2?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&tinyInt1isBit=false
          username: root
          password:

logging:
  config: classpath:log-config/log4j2-${spring.profiles.active}.xml
server:
  port: 8000
#server:
#  port: ${random.int[20000,60000]}
